project:
  type: website
  output-dir: docs/
  
website:
  title: "Kinlie Gohl Website"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: Gohl, Kinlie_Curriculum_Vitae.pdf
      - text: "Research"
        menu: 
          - href: Reading Notebook.qmd
            text: Reading Notebook
          - href: Association Rules.qmd
            text: Association Rules
      - text: "Reflections"
        menu: 
          - href: Breiman and Shmueli.qmd
            text: Breiman and Shmueli Comparison
          - href: AI and Originality.qmd
            text: AI and Originality
          - href: Using AI in Projects.qmd
            text: Using AI in Projects
          - href: Humans and Knowledge.qmd
            text: Humans and Knowledge
          - href: Machine Learning Pipeline.qmd
            text: Machine Learning Pipeline
          - href: Prediction vs Explanation.pdf
            text: Prediction vs Explanation
          - href: Text Mining Patterns.qmd
            text: Text Mining Patterns
      - text: Assignments
        menu:
          - href: Assignment 1.pdf
            text: Assignment 1
          - href: Assignment 2.pdf
            text: Assignment 2
          - href: Assignment 3.qmd
            text: Assignment 3
format:
  html:
    theme:
      - pulse
      - brand
    css: styles.css
    toc: true

editor: visual

