---
title: "About"
---

About me! My name is Kinlie

I am a first year masters student in the Social Data Analytics and Research program at the University of Texas at Dallas. I completed my bachelors in Psychology from the University of Texas at Arlington. After graduating, I become a lab manager for the Kennedy and Rodrigue Cognitive Neuroscience lab at UTD.

I was interested in social data analytics because I wanted to broaden my realm of knowledge. I do not have strong coding or statistical skills, but I know that these skills would better equip me for jobs in psychology and data analysis.

My research interests include: The use of psychedelics on treatment resistant depression. I believe that we should expanding the number of modalities available for mental health disorders in order to help as many people as possible.

Some fun facts about me:

-   I am left handed
-   I have one small Pug-Pomeranian dog
-   I am an avid chess and Tetris player
-   I enjoy archery, crocheting, and playing video games
