---
title: "AI and Originality"
---

With the emergence of AI, ChatGPT, and homework help, it has become easier to think less and have the computer work more. People are becoming more unoriginal and relying on AI and the internet to do the thinking for them. Previously when writing a research paper, a person would have to sift through articles, Google Scholar, and books to find evidence that supports their topic, but now, ChatGPT is able to populate 10 articles that directly correlate to the research in seconds. AI is decreasing our cognitive load and capabilities because it can give us precise information, ideas, answers, and work within no time. We no longer have to sit and think up research ideas; we can simply ask ChatGPT and it will have as many ideas as we want that all relate to our interests.

Our creative endeavors have also changed with AI. A major controversy with AI is its use in art. AI creates new ideas, paintings, music compositions, videos and stories and takes away from humans doing the thinking. We don’t have to put in the mental effort to think of a new story or a new project idea because AI can generate those same ideas in a fraction of the time, saving humans time and energy. Even though those creative projects still exist and there is a huge market for it, there are also many companies and people who prefer to use AI to get the same result with half the effort.

Ai is built with an algorithm that is honestly lackluster. It is generic and the “safe option”. AI won’t give you the out-of-the-box topics or ideas you’re searching for because it is trained to appeal to the masses. And people stop searching for those far fetched ideas because AI is also training us. When we are only given the safe option or the average response, we are becoming more accustomed to accepting mediocrity and not thinking outside of what we know. Often, the “good” ideas are found through trail and error or human connection and if we are not given the opportunities to fail or connect, we won’t achieve the same results. The “safe option” can also refer to word choices. There are countless times where I have googled synonyms for “discussed” and used the first synonym to pop up instead of using my own writing style and thinking about what I would want to use. We are becoming conditioned to ignore our own thoughts and go with the “safe option” we know will be more understood.

AGI stands for artificial general intelligence. It is an advanced form of AI that can process and learn at an above or equal level to human intelligence. Is it able to apply knowledge learned in one area to another unrelated area with ease. AGI affects scientific research because it will make it easier to connect different scientific disciplines and papers in ways that people would not normally think of. AGI will also be able to understand information, make correlations, understand causation, and design experiments to prove the theories without any effort or time. Effectively, AGI would be able to do the same thinking and designing that a human can do in no time and on a greater scale. If AGI were to be used in research, I believe it would negatively impact researchers, their jobs, and change the way research is conducted. The need for data analysts would decrease and researchers would no longer have to think up research ideas. Overall, AGI in research would drastically change the way research is conducted and change a researcher’s role to more of an overseer than a creator.
