---
title: "Humans and Knowledge"
format: html
---

Humans and Knowledge


There are multiple ways that humans acquire knowledge, through experiencing the world around them, shared knowledge, self-reflection, reasoning, and gut instincts. Humans use their senses: sight, smell, touch, taste, and sound, to learn about their environment. We learn that ice is cold by tasting or feeling the cold. We touch a cactus and get pricked; we learn that you can’t grab a cactus with your bare hands because you will get injured. Shared knowledge is also a way that humans acquire knowledge. Stories passed down by generations have lost credibility since they are not from the source but are still beneficial to understanding our history and sharing past experiences. We learn that certain berries are poisonous because people have died when consumed. We learn of the hardships and tribulations people in history faced because of the stories of those who came before us. 

Similarly, self-reflection allows us to gain knowledge. When we reflect, we look back on our past experiences and conclude about the best outcomes and how we feel. Pattern recognition helps us find our triggers for certain emotions and how people will react if we act in a specific manner. Reasoning is another main type of knowledge acquisition. We use deduction and logical fallacies to determine what makes logical sense and what doesn’t. We know that we have a brain inside our heads without most of us ever seeing our own because every person who has died or been operated on, has had a brain. Therefore, we can deduce that because everyone else has a brain, we do as well. Lastly, gut instinct lets us acquire knowledge. We don’t inherently know that a bear will kill us, but being chased and filled with adrenaline doesn’t allow us to stick around to find out. We run in the chance that the bear might kill us. This also goes for suspicious situations. If there is a person that makes us feel uneasy but there is not concrete evidence as to why, we put our guard up and hold precautions anyways or try to create as must distance as possible from the threat. Similarly, how a pregnant woman knows to push when giving birth without directly being told. It is her instinct and she does it even without knowledge as to why. 


Knowledge vs Information


Knowledge is different than information in that information does not have to be interpreted. Information is facts and direct knowledge that does not require justification or interpretation. The capital of the Canada is Ottawa. This statement is information because it cannot be debated and does not require justification. Knowledge can be complex, debated, and changed by beliefs or values. Knowledge is accompanied by understanding, information is facts that do not have to be understood to be true. If I were to say “blood is sacred” that would be the knowledge to a Jehovah’s witness member, but it can be refuted by other religions, therefore it is not information. However, if I were to say “blood has a pH between 7.35 and 7.45”, that is information since it is a fact. 


AI Discrepancies


AI has a multitude of issues overall, but when using AI, some common issues include false information, fabricated statistics, biases, and dated usage. For instance, when using ChatGPT or AI writing software, there have been times when the AI will create fake sources or citations to argue a point. It will mislead the user and strengthen its argument with sources that are misconstrued or fabricated. This has also been the case for numbers and statistics. There have been times when an AI model will use false numbers to create a graph or study that will ideally fit with the argument it is trying to make. There are also biases within AI systems. If an AI system is created by Amazon, it will resist expressing negative information about Amazon or push the user to use Amazon in their daily life. Lastly, AI models can only be as relevant as the software they are using. When new trends, slang, or research immerges, AI can only keep up if the software running is also up to date. Therefore, some AI models may be dated and use research or facts from years ago when current research has already proven that theory wrong. 

The patterns within AI discrepancies all relate back to the speed that AI should work. False information and statistics are fabricated because it is quicker to create false information than to review thousands of articles to pick the ones best catered to the argument. AI can only be so modern because it takes time to update models with newer trends and information than it is to rely on older information that the models are already aware exist. And this is an issue among many AI models; writing software like ChatGPT, self-driving cars and road closures or construction, and AI social media with current events. 
