---
title: "Machine Learning Pipeline"
format: html
---

A machine learning pipeline is a sequence of steps that make sure data is correctly prepared, models are trained, and results are evaluated properly. When starting my first machine learning pipeline, I used the National Assessment of Education Progress (NAEP) database since that is the database we are using for our project. It is also a state-level education dataset that works well with machine learning. The first step was to collect the data and determine what grade levels we would be looking at. We are looking at 4th and 8th grade level reading scores. The next step is to clean the data and rename or delete missing values and label the categories. These are some of the first steps when starting the machine learning pipeline. 


Error Analysis

Accuracy is classified as a single number and can be identified through the number of correct predictions. What accuracy does not tell us is where the model made mistakes and the patterns in if certain groups were affected differently. Error analysis reveals these mistakes, biases in groups, weaknesses in the learning process, and areas where the model did not pick up patterns or relationships. 
	
Over fitting is where the model understands the data too much and makes false connections. As well as capturing noise instead of patterns and does not know how to work with new data because it is too familiar with one dataset. Overfitting often mistakes noise for knowledge. Knowledge is where true patterns are shown in the data and shows the real structure of the data. Noise is the random errors or fluctuations that can happen in a dataset. Overfitting picks up on these fluctuations and mistakes them for actual patterns. For instance, since there is no personal student information in the pipeline, each student would have been assigned a number. Overfitting would take the noise, the participant’s number, and create connections to the data that has no real meaning. This creates a fragile and irrelevant relationship with the data that is not of any use for finding patterns and connections. If we were finding knowledge in the dataset, we would see connections between reading scores being lower with students on government assistance, or reading scores being higher in higher-income areas.  
