---
title: "RAG in Research"
format: html
---

Retrieval-Augmented Generation is an AI system that retrieves documents from a database and generates answers using a language learning model. Even though the model has been trained on the specific database, RAG lets the model explore possibilities before answering. This matters for research because RAG addresses the limitations inherent in traditional language learning models. RAG focuses on using up-to-date knowledge from current literature and datasets. Compared to LLMs, which often rely on familiar past information rather than the most up-to-date information. RAG also uses data outside of its training realm. It will reach for articles and datasets it’s not trained on to provide the best response. RAG is also well-trained in providing citations for the sources it’s pulling information from.

Grounding generation in retrieved documents changes the trustworthiness of AI output by reducing hallucinations, allowing for verification, improving evidentiary support, and improving pipeline quality. To reduce hallucinations, RAG focuses on real documents instead of creating fake reports. Hallucinations can still occur if context is ignored, but the likelihood is less compared to LLMs. RAG allows for verification by using real sources to back up claims. Instead of relying on the model’s trained responses, RAG relies on the source to support its claims. RAG improves evidentiary support by using external sources rather than using the trained database to make predictions. Lastly, RAG improves the pipeline quality because it focuses on document quality instead of how it can integrate the data into the model, how well the model can learn the data, and the data quantity.

Recent criticism of RAG is on what RAG determines to be “good” data, unrelated information, noise, and context in sources. RAG uses “better” data than LLMs, but what is the threshold for how it determines what good data is? If it is retrieving biased and irrelevant data, then the outputs will be biased and unusable. If RAG combines a new document with prior information, the claims may not add up or be relevant to the questions being asked. RAG uses a lot of information and documents, but with more documentation, there will be more noise. RAG may find connections where there are none or create answers to questions with no correlation. RAG may also struggle with conflicting sources and using data in context. RAG is good at pulling from a variety of sources, but using those sources in the context of the papers is important to understand their claims. Using multiple sources is beneficial to have a broader understanding but using two sources that do not relate to support one’s claim will pose a problem.

To improve RAG, it is important to improve retrieval quality, reduce noise, fact-check, detect contradictions, and use RAG with other techniques. Improve retrieval quality by filtering the data RAG uses and creating proper chunks for the system to digest. Reduce noise by deleting duplicates and selecting fewer but higher-quality chunks of data. Detect contradictions by fact-checking sources and rerunning unsupported claims. Using RAG with other techniques, like other systems and multiple models, creates the best output when using AI.
