---
title: "Reading Notebook"
format: html
---

My reading notebook starts by listing out the book’s information. This includes the title, genre, author, type of reading, and what I hope to accomplish by the end. Once finished, I also like to write a summary of the reading and rate it out of 5 stars on understandability, captivation, length to meaningful content ratio, and how effectively it helped me reach the reason why I read it to begin with. I also include key points, vocabulary I didn’t understand, and meaningful arguments that made me think. If I am reading a research article or an academic book, I will list out a question or two I still have about the reading to bring forth discussion and future research. 


Reading Routine


My reading routine varies depending on the type of reading and the length. If I am reading an academic article, I will read at my desk in the evening with my ceiling fan light on. This allows me to stay alert and really digest what I am reading. My desk also gives me access to my notes or paper to jot something down. If I am reading for pleasure, I will read in a lounge chair at any time of the day but particularly at night. I will have dim lights or a lamp nearby and I am usually with my dog and a blanket. 


Reading Effectiveness Strategies


I cannot read in total silence so I will sometimes turn on the tv to a channel I’m not interested in or open my window to listen to cars going by. I also turn my phone off for every material I read because my phone easily distracts me and I will lose focus. I will also look up other people’s understandings of readings to compare my own synopsis and make sure that I understand key details. I will go back and reread if I am missing something that other people are pointing out. Understanding what I am reading is the most important part of research and academic reviews. Rereading specific sections, summarizing after a few pages, breaking difficult concepts down into smaller parts, and asking questions are critical components of effective reading. One cannot simply read an article, lack understanding and say they have a grasp on the material and research being conducted. 
