---
title: "Using AI in Projects"
---

AI has many uses, from creating ideas, timelines, to-do lists, providing more defined questions, and breaking projects down into smaller steps. To start using AI, familiarity with AI models is crucial to understanding how AI can help you in your projects. Once comfortability with the AI model is established, you can use AI to help you brainstorm topics or refine research questions. Then, AI can help create a to-do list of the steps needed to produce the project. Next, AI could create a timeline of how long each step should take and how much time you should put into each section. This would give you a good estimate of the project length and how much effort is expected with each step. AI can even help you create the first rough draft of the project which helps ease the “blank page” anxiety most people have when first starting out. AI is incredibly helpful with creating rough drafts of assignments or projects but should never be used as the final draft. There are many steps we should use after using AI in the creation process to ensure originality and authenticity, including fact checking, editing, final draft creation without the use of AI, and AI documentation because not all the work was your own creation. AI is helpful with the brainstorming process and checking for mistakes but there is only so much AI can do, much of the work still falls on the individual to do and create.

The two AI models I will be using on my project are ChatGPT and Grok. AI can be leveraged to speed up learning by summarizing articles, simplifying complex information, and teaching you how to ask more specific questions to achieve the desired results. I will also use AI to build an outline and curate steps that best fit my workflow and the project I want to create.  
